[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "caplib"
authors = [{name = "CapRiskTech", email = "graziella@caprisk"}]
dynamic = ["version", "description"]
